### ISSUE TITLE
Current Status?

### ISSUE THREAD

**Issue by bnb** [nodejs/education#1]
Hello!

What is the current status of the Node Education WG/group/whatever you want to call it so far? I'd really like to start working on this now that I have free time again. I'm willing to draft ideas, call on the community, whatever it takes to get this rolling!

Thanks.

**Comment by mikeal** [comment]
Tracy has done a lot and I'm sure she will comment here soon but she's currently running EmpireJS so I doubt she'll get to it before next week :)

**Comment by bnb** [comment]
Okay, sounds good! Thanks, @mikeal.

**Comment by hackygolucky** [comment]
@bnb I'll be filling in the roadmaps other than cert soon, but if you have thoughts on what you've heard from folks wanting for learning node that we can support, I'd love to see them here!

**Comment by kristianjaeger** [comment]
Please let me know if I can assist. I was surprised that StrongLoop dropped their cert. Cheers.

**Comment by hackygolucky** [comment]
@kristianjaeger Watch for more issues in this repo and please give input! I'll post next steps when there's a little more direction from a meeting I have after this Thursday.

**Comment by kristianjaeger** [comment]
Hello @hackygolucky , any updates?  Thanks.

**Comment by cdnadmin** [comment]
Currently trying to convince a company to hire me to do this full time.  :-)   Let's see how it goes; nevertheless, would like to help--especially with [this](https://github.com/nodejs/education/blob/master/ROADMAP.md#certification), if possible!

**Comment by kristianjaeger** [comment]
It's been over a month, where are the updates please. :)

**Comment by DEspino-Specialized** [comment]
Hi, I'm also interested on a Cert program or a Cert Exam. Is there any immediate plan for this? I have this a end of year goal (lol). I've read that this could be an alternative for this http://www.ibm.com/developerworks/middleware/services/badges/... not sure if this could be recognized as a certification of language and tools domain.

Thanks a lot

**Comment by bnb** [comment]
Hey @DEspino-Specialized! There actually is a Certification program being implemented right now. I don't know a timeline on when it will be up and running at full capacity, but it's in the works right now.

Taking a look at the IBM link you provided, it's an interesting concept. While they look like an _awesome_ effort by IBM, the Node.js Certification, as I understand it, would be a much more comprehensive verification of Node.js preparedness in a professional environment.

**Comment by DEspino-Specialized** [comment]
Thanks a lot @bnb ... I will follow up on this closely  :)

**Comment by hackygolucky** [comment]
@kristianjaeger @DEspino-Specialized @cdnadmin I think this issue is in regards to the initiatives overall and not just the cert, but to answer the question about the certification timeline--it's looking to be on track for end of Q1 2017. 

As for 'current status' in general, I'm trying to figure out a better system for updating folks in more than just a GitHub repo on the education initiatives, since so much of what is being done is very large-scale, long-term, and not code. This will very likely be in a monthly blog posting cadence that is also backed up as markdown files in this repo. Many of the interested parties for this work aren't just devs, so making sure I communicate with all of the channels is important 🎉
