### ISSUE TITLE
Why a certification?

### ISSUE THREAD

**Issue by boneskull** [nodejs/education#5]
@hackygolucky mentioned in #3 that the discussion of whether or not #3 should even be happening is off-topic. Not sure I agree with that logic, but here's a new issue. 

My concerns include:

- Where did the idea come from?
- Who made the decision to create a certification?  Was there community input?
- Why was the decision made?
- What problems does it solve?
- How do we know certification is the answer to these problems? What had happened in other 
industries? Is there science behind this?
- How does paying for a certification help or hinder community inclusivity efforts?  I noted some qualified for the certificiation may not have the means to pay.

- ~~How does this fall under the realm of "education"?~~ A certification *in and of itself* isn't "education", but a structured training program, giving developers the tools to pass certification, is.
- ~~is there an education WG? Why or why not?~~ There's an "Education Advisory Group" as per [this article](https://www.linux.com/blog/qa-tracy-hinds-improving-education-and-diversity-nodejs), but I cannot find further information on membership, meeting notes, etc.

**UPDATE**: Mostly formatting; answered two of my questions.

**Comment by boneskull** [comment]
As per the article (@hackygolucky, please excuse me if I don't provide enough context in these quotes),

> Certifications are extremely important to developers that have previous coding experience and are employed by companies who require it for hiring or promotions. 

Is it not incumbent on the company to hire or promote based on factors *other* than a certification, if a certification does not exist?

> Those that have experience with these languages have expectations to have something similar when they convert to newer platforms/languages like Node.js.

I read this as "people have the expectation they should exist, therefore they should exist."  Just because it's common in other technologies doesn't necessarily mean Node.js should have a certification program.

> Certifications can also be useful for what we see often in the Node.js ecosystem — smaller companies and consultancies. It could be an interesting space when a group of engineers can show that they have their certifications and establishes them as competent and potentially more competitive than another group that isn’t quite there yet.

This seems like speculation; are there studies that show this is true?

@hackygolucky, given that you were in fact hired by the foundation with a mandate of establishing a certification program, I can understand that questioning its need or legitimacy could be a charged topic.  In general, promoting education around Node.js is a *good thing*, and I'm glad the Foundation has found you to organize the efforts.

My aim here is to understand the reasoning behind the certification effort.  I'm having trouble connecting the dots from the original idea--"How about we create a certification program?"--to where we are today.

**Comment by kristianjaeger** [comment]
Just a thought but you could participate / contribute if you choose to do so.  If you don't agree then perhaps agree to disagree??

**Comment by boneskull** [comment]
@kristianjaeger Participate in what?

**Comment by kristianjaeger** [comment]
https://github.com/nodejs/education/issues/3

**Comment by boneskull** [comment]
@kristianjaeger I see.  Unless someone cares to convince me otherwise (by answering the questions above), I'm not interested in determining the format for a certification exam unless that format is "no exam".

**Comment by hackygolucky** [comment]
@boneskull 

There are a number of justifications for a certification. You don't have to fit in the category of the folks who need it in order for it to be needed in Node.js. :) I appreciate you asking questions because it helps disseminate information to more people also curious.

It's my fault for not publishing the findings for the justification of the certification beyond the interviews I've had where I've talked about it. I'd been so busy emailing and talking to folks around the world in-person that I didn't take the time to share that. That's absolutely my bad.

A few reasons I came upon while researching:
- users in China(Beijing and Shanghai) approached me during Node Live travels to share needing it for work or to advance, both from large companies and smaller consultancies
- folks coming from .net and java communities have expressed feeling very comfortable with the expectation of getting a certification after following a training program to learn or up their game(this is a fast growing user base of Node)
- Many members of the foundation(the folks who are helping financially supporting the Node.js project via the foundation membership) expressed how useful it would be for their own employees.
- I’ve talked to devs in the US who didn’t go to school but got certs and it’s the only way they’ve gotten jobs or promotions.

A number of folks in various parts of the world online(via emailing me), in-person at events, and in these threads(#3 for example) have also reiterated it's usefulness.

Granted, any of the folks I've talked to and the numbers I've seen regarding needs in Node.js and certifications in the tech world cannot be asssumed to fit every individual working in Node.js. While these individually can be considered anecdotal in nature, when added up it was pretty clear to me thus far it is needed. I was hired in part to make this assessment, research that we're covering a good range of user types in the ecosystem, and if evidence existed to back it up, move forward.

So, we're moving forward!

**Comment by boneskull** [comment]
@hackygolucky Thanks for responding.  I'm a bit frustrated by the response; in some cases you've simply repeated what you wrote before, and declined to address other questions.

You wrote,

> users in China(Beijing and Shanghai) approached me during Node Live travels to share needing it for work or to advance, both from large companies and smaller consultancies

and I wrote previously,

>Is it not incumbent on the company to hire or promote based on factors other than a certification, if a certification does not exist?

It seems like the logic here is "companies want certifications, and Node.js developers are failing to avance because they have no certifications, therefore we must offer certifications."  Instead, is the problem that certifications are seen as necessary by companies and hiring managers?  And if they were not, then we wouldn't need them?

You also wrote,

> folks coming from .net and java communities have expressed feeling very comfortable with the expectation of getting a certification after following a training program to learn or up their game(this is a fast growing user base of Node)

and I wrote previously,

> I read this as "people have the expectation they should exist, therefore they should exist." Just because it's common in other technologies doesn't necessarily mean Node.js should have a certification program.

So it feels like this wasn't really addressed--I mean, training is great, and will do a lot for Node.js.  But, "I want a certificate at the end of my training because my *other* training gave me a certificate" sounds unconvincing, at least to me.

> I’ve talked to devs in the US who didn’t go to school but got certs and it’s the only way they’ve gotten jobs or promotions.

This is also anecdotal.  What I'd really like to see here is data.  How many people are being held back by the lack of certification?  What, instead, could we do to challenge corporate cultures that expect certifications?  There are other ways to demonstrate ability; certifications are just one (controversial) way.

> Many corporate members of the foundation(the folks who are helping financially supporting the Node.js project via the foundation membership) expressed how useful it would be for their own employees. We currently have 26 member companies. They employ a fair amount of devs.

How would it be useful for the employees?  

I apologize if I am mistrustful of corporate members (who are not "folks", btw) which claim to promote this effort "for the good of their employees".  Now, this doesn't mean providing "use" to their employees isn't necessarily a *side effect* of the certification effort--but corporations act in the interest of themselves.

If the corporations want better training, that's something to which they can pledge resources, *regardless* of a certification effort.  And I would even be happy to help with a structured effort around training!

> A number of folks in various parts of the world online(via emailing me), in-person at events, and in these threads(#3 for example) have also reiterated it's usefulness.

I noticed this as well, and I'm going to guess it's because businesses in these regions rely heavily on certifications to make decisions around hiring and promotion.

> You don't have to fit in the category of the folks who need it in order for it to be needed in Node.js.

I don't need it, no.  If those claiming to need it are driven by "companies won't hire or promote without it", maybe the resources dedicated to a certification effort would be better spent educating companies on how to hire and promote Node.js developers.

I wrote,

> How does paying for a certification help or hinder community inclusivity efforts? I noted some qualified for the certificiation may not have the means to pay.

Can you please speak to this?  This was my original concern.  How doesn't (or does?) the certification effort increase diversity?

> I was hired in part to make this assessment, research that we're covering a good range of user types in the ecosystem, and if evidence existed to back it up, move forward.

Sorry to push here: so if you (and only you?) decided there wasn't enough evidence, this effort would have been halted?

> So, we're moving forward!

Yes, I realize that the decision has already been made, but it won't shut me up yet. 😏

**Comment by piranna** [comment]
> There are other ways to demonstrate ability; certifications are just one
(controversial) way.

The best one, having open source contributions published on public repos
and/or npm registry... that could respald and be itself one of the
measurements to achieve the certificate.

> If those claiming to need it are driven by "companies won't hire or
promote without it", maybe the resources dedicated to a certification
effort would be better spent educating companies on how to hire and promote
Node.js developers.

I agree.

**Comment by TheAlphaNerd** [comment]
Hey ya'll. I can empathize with where you are coming from. While you may not philosophically agree with the need for certifications in the industry as a whole, we are not going to really get anywhere by boiling the ocean here.

The purpose of this certification is to help people. 

The number of people, many of whom have not been active in the project before, that are raising their hands out of interest in the other thread is a great litmus test to the fact that such an effort will likely engage more people in the community.

It is likely that Tracy is not going to have the bandwidth to engage in an extended debate this today as she is busy at Node Summit, and prepping for Cascadia JS next week.

While I do not have all of the information that Tracy does, I would be more than happy to continue this discussion on another medium if you are interested. My [dm's are open](https://twitter.com/thealphanerd) and you can privately message me on irc `/msg thealphanerd oh hai`

I do wish to disclose that I am a paid employee of IBM who works full time on core.

**Comment by jesstelford** [comment]
Miles, I don't think it'll be beneficial to move the discussion to private channels. I'm here to show my support for the questions @boneskull is asking.

In particular, the elephant in the room which has yet to be addressed:

> How does paying for a certification help or hinder community inclusivity efforts? I noted some qualified for the certificiation may not have the means to pay.

>  I'd been so busy [..] talking to folks around the world in-person [...] and many more at Node Live events [..] Node Summit, and [..] Cascadia JS

It appears there may be bias in the self-reported survey data being gathered here; each of those events is an expensive thing to attend. The folks who are there are by default the folks who can afford (or who's employers can afford) to pay for a certification. Have you talked to any of the community (read; diversity / disadvantaged / free) efforts and asked if their students would like such a certification and if they could even afford one?

> You also wrote,
> 
>> folks coming from .net and java communities have expressed feeling very comfortable with the expectation of getting a certification after following a training program to learn or up their game(this is a fast growing user base of Node)
> 
> and I wrote previously,
> 
>>  I read this as "people have the expectation they should exist, therefore they should exist." Just because it's common in other technologies doesn't necessarily mean Node.js should have a certification program.
> 
> So it feels like this wasn't really addressed--I mean, training is great, and will do a lot for Node.js. But, "I want a certificate at the end of my training because my other training gave me a certificate" sounds unconvincing, at least to me.

This is the same argument which led to having `class` introduced into the language, which was its own controversial topic (I sit firmly on the side of; it was never needed, and shouldn't have made its way in just because folks couldn't be bothered to learn about prototypes or closures).

I feel @boneskull's questions should be addressed point by point before any further actions are taken by the foundation, as opposed to any kind of gut feel.

**Comment by TheAlphaNerd** [comment]
@jesstelford I was not trying to imply that conversation should only happen off the record, more that it might be faster and easier to find a baseline doing so. Mostly wanted to offer somewhere to chat while others are busy

Fwiw the Node Live events were all free to attend. I'll leave it to @hackygolucky and others from the foundation to answer more specific questions.

**Comment by boneskull** [comment]
I spoke with @TheAlphaNerd offline about this, mainly for bandwidth.  He was able to give me another perspective to which I could relate.

And I'd like to apologize to @hackygolucky, @TheAlphaNerd and anyone else who thought I came off as abrasive and/or aggressive.  I have been described as "blunt", and am not skilled at masking frustration.  

While I feel others and myself have made good and valid points, there's nothing to be done here.  GitHub issues just aren't the right forum for this type of thing.  I should have known better, and again apologize for derailing #3.

So, if in the future, someone like @hackygolucky wishes to post more information on a blog about this issue--and possibly address concerns that myself and others have raised in an "official" capacity--it'd be appreciated by myself and others.  

I'm going to close and unsubscribe from this issue.  If anyone feels the need, I can be "tweeted" at `@b0neskull` or [emailed](/boneskull).
