### ISSUE TITLE
Will the certification focus on Node.js using ES5, ES6 or both?

### ISSUE THREAD

**Issue by kristianjaeger** [nodejs/education#9]
Gracias!

**Comment by bnb** [comment]
Fairly certain that's TBD. The curriculum hasn't been defined yet as far as I know, so choices like this - what is going to be in the certification process and what is not going to be in the certification process - will be made when the curriculum _is_ defined.

**Comment by kristianjaeger** [comment]
@bnb Yes, please see Tracy's readme. cheers.

**Comment by kristianjaeger** [comment]
@hackygolucky Did I misunderstand what you posted "Please participate. File issues, PRs, and create the community you'd like to be a part of. If you need inspiration or have questions that you'd like to ask outside of issues, reach out to tracy.hinds@linuxfoundation.org"?  I thought that you were encouraging folks to post issues, etc...

**Comment by hackygolucky** [comment]
@kristianjaeger We love issues being posted. This one was closed because it was answered by @bnb and there was no further discussion needed on this issue. I'm cleaning up as I go. 

The next phase of the certification content discussion will happen in the workshop sessions being scheduled. After that, we'll reach out to a wider group to ensure what the JTA group determined as good domains to cover is something the larger community agrees will be useful.

**Comment by kristianjaeger** [comment]
@hackygolucky  Okay, sounds good. Thanks.

**Comment by rsp** [comment]
@hackygolucky When will be the time when questions about the certification like this one by @kristianjaeger will be discussed rather than closed? Any timeline on that? Also, should those questions be reposted when the time is right or will the closed questions get reopened then? Thanks.
